import { Education } from '../core/models';

export const EDUCATION: Education[] = [
  {
    id: 'ma-sociology',
    degree: 'Master of Arts',
    field: 'Sociology',
    institution: 'Freie Universität Berlin',
    location: 'Berlin, Germany',
    startYear: 2022,
    endYear: 2024,
    grade: '1.8',
    supervisor: 'Prof. Dr. [Supervisor Name]',
    thesis: 'Social Cohesion and Integration: A Comparative Analysis of Migration Policies in the EU',
    coursework: [
      'Advanced Quantitative Research Methods',
      'Qualitative Social Research',
      'Migration and Integration Studies',
      'Labour Market Sociology',
      'Gender and Diversity Studies',
      'European Social Policy',
      'Social Inequality',
      'Organizational Sociology',
    ],
    logo: '/images/fu-berlin-logo.svg',
    highlight: 'Thesis awarded highest distinction',
  },
  {
    id: 'ba-sociology',
    degree: 'Bachelor of Arts',
    field: 'Sociology',
    institution: 'Freie Universität Berlin',
    location: 'Berlin, Germany',
    startYear: 2019,
    endYear: 2022,
    grade: '2.0',
    coursework: [
      'Introduction to Sociology',
      'Social Theory',
      'Statistics for Social Sciences',
      'Political Sociology',
      'Cultural Studies',
      'Development Studies',
      'Urban Sociology',
    ],
    logo: '/images/fu-berlin-logo.svg',
    highlight: 'Dean\'s List — Top 10% of cohort',
  },
];
