import { Experience } from '../core/models';

export const EXPERIENCE: Experience[] = [
  {
    id: 'intersport',
    title: 'Assistant Manager',
    organization: 'InterSport Voswinkel GmbH',
    type: 'full-time',
    location: 'Berlin, Germany',
    startDate: 'Nov 2023',
    endDate: 'present',
    responsibilities: [
      'Support store management with daily operations, staff supervision, and performance monitoring',
      'Oversee SAP system usage for sales, inventory, and reporting',
      'Execute visual merchandising strategies to align with brand identity and maximise sales',
      'Handle POS operations, cash management, and daily reconciliation',
      'Manage KHP online orders and ensure timely fulfillment',
      'Respond to customer and business correspondence via email',
      'Collaborate with teams to improve workflows and overall store efficiency',
    ],
    achievements: [],
    skills: ['SAP', 'Team Leadership', 'Visual Merchandising', 'POS Systems', 'Cash Management', 'Inventory Management'],
    kpis: [],
  },
  {
    id: 'zara',
    title: 'Cashier / Sales Advisor',
    organization: 'ZARA Deutschland B.V. & Co',
    type: 'full-time',
    location: 'Berlin, Germany',
    startDate: 'Nov 2022',
    endDate: 'Oct 2023',
    responsibilities: [
      'Delivered exceptional customer service and efficient transaction management',
      'Operated point-of-sale systems with accurate cash handling and accounting',
      'Applied product knowledge and sales techniques to drive revenue',
      'Collaborated with team members to maintain store standards and workflows',
    ],
    achievements: [],
    skills: ['Customer Service', 'Cash Handling', 'POS Systems', 'Sales Techniques', 'Teamwork', 'Product Knowledge'],
    kpis: [],
  },
  {
    id: 'flink',
    title: 'Inventory Associate',
    organization: 'Flink GmbH',
    type: 'full-time',
    location: 'Berlin, Germany',
    startDate: 'Dec 2021',
    endDate: 'Oct 2022',
    responsibilities: [
      'Prepared records of all incoming materials for internal and external suppliers',
      'Managed, monitored, and evaluated inventories for damage checks',
      'Analysed customer requirements for the sale of products',
      'Supported overall inventory control activities',
    ],
    achievements: [],
    skills: ['Inventory Management', 'Record Keeping', 'Supply Chain', 'Quality Control'],
    kpis: [],
  },
  {
    id: 'dewi-back',
    title: 'Production Assistant',
    organization: 'Dewi Back GmbH',
    type: 'full-time',
    location: 'Berlin, Germany',
    startDate: 'Jun 2020',
    endDate: 'Jun 2021',
    responsibilities: [
      'Optimised the production process in daily business operations',
      'Performed quality checks for product range before packing',
      'Resolved product issues and rectified them for production',
    ],
    achievements: [],
    skills: ['Production Management', 'Quality Control', 'Process Optimisation'],
    kpis: [],
  },
  {
    id: 'hakka-dhaka',
    title: 'Manager — Team Lead',
    organization: 'Hakka Dhaka',
    type: 'full-time',
    location: 'Dhaka, Bangladesh',
    startDate: 'Nov 2017',
    endDate: 'Sep 2019',
    responsibilities: [
      'Prepared monthly budget for inventory and communicated with vendors',
      'Actively supported payroll management',
      'Prepared monthly reports for all transactions',
      'Improved and optimised working processes for greater efficiency',
      'Planned and coordinated promotional events',
      'Assisted in the hiring process by conducting interviews',
      'Handled all administrative tasks and team coordination',
    ],
    achievements: [],
    skills: ['Budgeting', 'Payroll', 'Vendor Management', 'Reporting', 'Team Management', 'Recruitment'],
    kpis: [],
  },
  {
    id: 'taste-of-lanka',
    title: 'Account Manager',
    organization: 'Taste of Lanka',
    type: 'full-time',
    location: 'Dhaka, Bangladesh',
    startDate: 'Jan 2015',
    endDate: 'Sep 2017',
    responsibilities: [
      'Maintained all kinds of customer requests and accounts',
      'Managed and entered cost changes with proper documentation',
      'Reconciled all inventory balances',
      'Provided appropriate solutions for customer requests',
    ],
    achievements: [],
    skills: ['Account Management', 'Customer Relations', 'Documentation', 'Inventory Reconciliation'],
    kpis: [],
  },
];
