import { Experience } from '../core/models';

export const EXPERIENCE: Experience[] = [
  {
    id: 'ra-fu-berlin',
    title: 'Student Research Assistant',
    organization: 'Freie Universität Berlin – Department of Sociology',
    type: 'part-time',
    location: 'Berlin, Germany',
    startDate: 'Oct 2023',
    endDate: 'present',
    responsibilities: [
      'Support senior researchers in designing and executing qualitative studies on migration and social cohesion',
      'Conduct semi-structured interviews and focus groups with migrant communities in Berlin',
      'Code and analyse qualitative data using MAXQDA and Atlas.ti',
      'Review literature and compile annotated bibliographies for ongoing research projects',
      'Prepare policy briefs and academic reports for external stakeholders',
    ],
    achievements: [
      'Co-authored a working paper on housing discrimination submitted to a peer-reviewed journal',
      'Reduced data processing time by 35% through standardised MAXQDA workflows',
      'Presented preliminary findings at the departmental research colloquium',
    ],
    skills: ['Qualitative Research', 'MAXQDA', 'Atlas.ti', 'Policy Writing', 'Academic Writing'],
    kpis: ['15 interviews conducted', '3 focus groups facilitated', '1 working paper co-authored'],
  },
  {
    id: 'project-coord-ngvb',
    title: 'Project Coordinator',
    organization: 'Neue Gesellschaft für Bildung und Beratung e.V.',
    type: 'part-time',
    location: 'Berlin, Germany',
    startDate: 'Jan 2023',
    endDate: 'Sep 2023',
    responsibilities: [
      'Coordinated a EU-funded integration project targeting newly arrived migrants',
      'Managed relationships with 20+ partner organisations and public authorities',
      'Organised and facilitated workshops, info sessions and community events',
      'Monitored project progress against KPIs and prepared donor reports',
      'Supported grant applications and fundraising strategies',
    ],
    achievements: [
      'Successfully reached 300+ participants over the project period',
      'Secured a follow-up project grant of €80,000',
      'Reduced administrative overhead by 25% through improved project tracking tools',
    ],
    skills: ['Project Management', 'Stakeholder Management', 'Grant Writing', 'Monitoring & Evaluation'],
    kpis: ['300+ participants reached', '€80K follow-up grant secured', '20+ partners managed'],
  },
  {
    id: 'intern-policy',
    title: 'Policy Analysis Intern',
    organization: 'Sachverständigenrat für Integration und Migration (SVR)',
    type: 'internship',
    location: 'Berlin, Germany',
    startDate: 'Apr 2022',
    endDate: 'Sep 2022',
    responsibilities: [
      'Analysed immigration and integration legislation at federal and EU level',
      'Conducted comparative policy analysis across EU member states',
      'Contributed to the annual SVR Migration Report 2022',
      'Prepared briefings for parliamentary committee hearings',
      'Monitored policy developments and synthesised implications for stakeholders',
    ],
    achievements: [
      'Three briefings adopted directly into the annual migration report',
      'Developed a comparative policy framework used by the team going forward',
    ],
    skills: ['Policy Analysis', 'Legislative Research', 'Report Writing', 'Comparative Analysis'],
    kpis: ['3 briefings published', '15 country analyses completed'],
  },
  {
    id: 'tutor-fu',
    title: 'Teaching Tutor — Social Research Methods',
    organization: 'Freie Universität Berlin',
    type: 'part-time',
    location: 'Berlin, Germany',
    startDate: 'Oct 2021',
    endDate: 'Mar 2022',
    responsibilities: [
      'Supported the introduction to social research methods course for BA students',
      'Facilitated weekly tutorial sessions on quantitative and qualitative methodology',
      'Provided individual academic mentoring and feedback on student assignments',
    ],
    achievements: [
      'Received 4.8/5.0 student satisfaction rating',
      'Developed supplementary learning materials used in subsequent semesters',
    ],
    skills: ['Teaching', 'Communication', 'Research Methods', 'Mentoring'],
    kpis: ['30 students tutored', '4.8/5 rating'],
  },
];
