import { Project } from '../core/models';

export const PROJECTS: Project[] = [
  {
    id: 'housing-discrimination',
    title: 'Housing Discrimination and Ethnic Minorities in Berlin',
    category: 'research',
    description: 'A mixed-methods study investigating discrimination in Berlin\'s private rental housing market against migrants and ethnic minorities, combining correspondence testing with qualitative interviews.',
    methodology: 'Correspondence testing (experimental); semi-structured interviews with 20 affected individuals and 8 landlords; content analysis of 200 rental listings.',
    outcome: 'Demonstrated statistically significant discrimination rates. Developed policy recommendations for the Berlin Senate.',
    impact: 'Policy brief submitted to Berlin Senate Department for Urban Development. Findings cited in local media coverage.',
    tools: ['SPSS', 'MAXQDA', 'R', 'NVivo'],
    skills: ['Mixed Methods', 'Policy Writing', 'Statistical Analysis', 'Qualitative Research'],
    year: 2024,
    featured: true,
  },
  {
    id: 'eu-migration-policy',
    title: 'Comparative Analysis of EU Migration Policy Frameworks',
    category: 'policy',
    description: 'Comparative analysis of migration and asylum policy across Germany, France, Sweden, and the Netherlands, examining coherence with EU-level directives and integration outcomes.',
    methodology: 'Document analysis of national legislation; expert interviews with 12 policy officials; process tracing; comparative case study design.',
    outcome: 'Identified key divergences in national implementation and proposed a convergence framework for EU integration benchmarking.',
    impact: 'Working paper submitted to the SVR; presented at a Berlin policy roundtable.',
    tools: ['Atlas.ti', 'Excel', 'Miro'],
    skills: ['Policy Analysis', 'Comparative Research', 'Expert Interviews', 'Policy Writing'],
    year: 2023,
    featured: true,
  },
  {
    id: 'labour-integration',
    title: 'Labour Market Integration of Refugees in Berlin',
    category: 'research',
    description: 'Longitudinal qualitative study examining barriers and enablers in the labour market integration of refugees three years after arrival in Berlin, with a focus on skills recognition and language acquisition.',
    methodology: 'Panel interviews with 25 refugees at two time points; institutional ethnography of employment agencies; secondary analysis of IAB data.',
    outcome: 'Identified systemic bottlenecks in credential recognition. Published as working paper.',
    impact: 'Presented at FU Berlin departmental colloquium; cited in follow-up grant application.',
    tools: ['MAXQDA', 'SPSS', 'R'],
    skills: ['Longitudinal Research', 'Ethnography', 'Panel Interviews', 'Statistical Analysis'],
    year: 2023,
    featured: true,
  },
  {
    id: 'gender-migration',
    title: 'Gender Dynamics in Forced Migration',
    category: 'academic',
    description: 'A feminist intersectional analysis of the gendered experiences of asylum-seeking women in Germany, focusing on access to healthcare, legal support, and social networks.',
    methodology: 'In-depth narrative interviews with 18 women; feminist grounded theory; intersectional analysis framework.',
    outcome: 'MA seminar paper; contributed to ongoing departmental research cluster on gender and forced migration.',
    impact: 'Seminar paper grade: 1.0 (highest possible). Shared with NGO partner Caritas for practitioner insights.',
    tools: ['MAXQDA', 'Miro'],
    skills: ['Feminist Research', 'Narrative Interviews', 'Grounded Theory', 'Intersectionality'],
    year: 2023,
    featured: false,
  },
  {
    id: 'integration-project',
    title: 'EU Integration Project Coordination — Neue Gesellschaft',
    category: 'community',
    description: 'Led coordination of an EU-funded project delivering language support, job preparation workshops, and social orientation for 300+ newly arrived migrants in Berlin.',
    methodology: 'Project management using PRINCE2 principles; participatory evaluation methods; stakeholder mapping.',
    outcome: 'Successful delivery of 24-month project. Monitoring reports submitted to EU funder on time and within budget. Secured follow-up funding.',
    impact: '300+ participants; €80K follow-up grant secured; 20+ partner organisations engaged.',
    tools: ['Jira', 'Notion', 'Excel', 'Power BI'],
    skills: ['Project Management', 'Monitoring & Evaluation', 'Grant Writing', 'Stakeholder Engagement'],
    year: 2023,
    featured: true,
  },
  {
    id: 'digital-exclusion',
    title: 'Digital Exclusion and Migrants in Berlin',
    category: 'research',
    description: 'Exploratory qualitative study on digital access and literacy barriers faced by low-income migrants in Berlin, with implications for digital government service delivery.',
    methodology: 'Focus groups with 3 groups of 8 participants each; participant observation at community digital hubs.',
    outcome: 'Policy brief with recommendations for digital inclusion interventions. Submitted to Berlin Senat Digitalisierung.',
    impact: 'Policy brief shared with 3 community organisations. Discussion paper cited in follow-up EU project application.',
    tools: ['MAXQDA', 'Miro', 'Notion'],
    skills: ['Focus Groups', 'Policy Brief Writing', 'Participant Observation'],
    year: 2022,
    featured: false,
  },
];
