import { Publication } from '../core/models';

export const PUBLICATIONS: Publication[] = [
  {
    id: 'ma-thesis',
    type: 'thesis',
    title: 'Social Cohesion and Integration: A Comparative Analysis of Migration Policies in the EU',
    authors: ['Hossain, T.'],
    year: 2024,
    abstract: 'This thesis employs a comparative case study methodology to analyse migration and integration policies across four EU member states. Drawing on mixed methods, including expert interviews and document analysis, it examines how policy design affects social cohesion outcomes among migrant populations.',
    keywords: ['integration', 'social cohesion', 'EU migration policy', 'comparative analysis', 'mixed methods'],
    pdfUrl: '/assets/publications/ma-thesis-2024.pdf',
  },
  {
    id: 'housing-paper',
    type: 'working-paper',
    title: 'Discrimination in Berlin\'s Private Rental Housing Market: Ethnic Minorities and Structural Barriers',
    authors: ['Hossain, T.', 'Müller, K.'],
    journal: 'FU Berlin Working Papers in Sociology',
    year: 2024,
    abstract: 'Using a mixed-methods approach combining correspondence testing and qualitative interviews, this paper provides evidence of systematic discrimination against ethnic minorities in Berlin\'s private rental housing market and proposes policy interventions.',
    keywords: ['housing discrimination', 'ethnic minorities', 'Berlin', 'correspondence testing', 'housing market'],
  },
  {
    id: 'labour-market-wp',
    type: 'working-paper',
    title: 'Skills Recognition Bottlenecks and Refugee Labour Market Integration: Evidence from Berlin',
    authors: ['Hossain, T.'],
    year: 2023,
    abstract: 'A longitudinal qualitative study examining systemic barriers in credential recognition experienced by refugees in Berlin over a three-year period. Findings point to administrative delays, language requirements, and lack of tailored support as key obstacles.',
    keywords: ['refugees', 'labour market integration', 'credential recognition', 'Berlin', 'qualitative longitudinal'],
  },
  {
    id: 'conference-dgsa',
    type: 'conference',
    title: 'Between Reception and Recognition: Gendered Experiences of Asylum-Seeking Women in German Healthcare',
    authors: ['Hossain, T.'],
    conference: 'Deutsche Gesellschaft für Soziale Arbeit (DGSA) Annual Conference',
    year: 2023,
    abstract: 'This paper presents findings from feminist grounded theory research on the healthcare experiences of 18 asylum-seeking women in Germany, highlighting how institutional procedures intersect with gender and migration status to create access barriers.',
    keywords: ['gender', 'asylum', 'healthcare', 'feminist grounded theory', 'intersectionality'],
  },
  {
    id: 'eu-policy-article',
    type: 'article',
    title: 'Toward a Coherent European Integration Framework: Lessons from the German Approach',
    authors: ['Hossain, T.'],
    journal: 'Berliner Journal für Soziologie',
    year: 2022,
    abstract: 'This article argues for a convergent EU-level integration framework, drawing on the comparative advantages of Germany\'s integration legislation while acknowledging its shortcomings in equity and participation.',
    keywords: ['European integration', 'immigration policy', 'Germany', 'EU governance'],
  },
  {
    id: 'digital-exclusion-brief',
    type: 'article',
    title: 'Digital Inclusion as a Condition for Social Participation: Migrants and the Digital Divide in Berlin',
    authors: ['Hossain, T.'],
    year: 2022,
    abstract: 'An exploratory policy-oriented study on digital access barriers among low-income migrants in Berlin, with implications for digital government service design and social inclusion strategies.',
    keywords: ['digital exclusion', 'social inclusion', 'migrants', 'Berlin', 'digital divide'],
  },
];
